server:
  port: 8082

spring:
    datasource:
    url: jdbc:postgresql://ep-lively-art-a115tsmd-pooler.ap-southeast-1.aws.neon.tech/learning
    username: neondb_owner
    password: npg_IWHV7d1igQNE
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: 41Dk432fD23423aADF342lkj234ADF987asdf987ADF345lkj345ADF345ADF345ADF
  expiration: 3600000
