server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

management:
  endpoints:
    web:
      exposure: "*"
  endpoint:
    gateway:
      enabled: true

jwt:
  secret: ${JWT_SECRET:41Dk432fD23423aADF342lkj234ADF987asdf987ADF345lkj345ADF345ADF345ADF}
